---
downloads: ~/.ansible-downloads/

# Docker
install_docker: true

# IDEs
python_developer: true
install_pycharm: false
pycharm_flavor: community
install_vscode: true
vscode_extensions:
  - shan.code-settings-sync

# browser configs
## Firefox config (note: default profile for Debian is default-esr)
configure_firefox: false
firefox_profiles:
  default-esr:
    extensions:
      - ublock-origin
    preferences:
      network.cookie.cookieBehavior: 1
      privacy.donottrackheader.enabled: true
      signon.rememberSignons: false
## Chrome install
install_google_chrome: true

# keyboard config
configure_international_keyboard: true
configure_c_cedilla: false

# SSH config
configure_ssh: true
configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# terminal config
## Guake config
configure_terminal: true
guake_keybinding: "F12"

## ZSH config
install_zsh: true
zsh_default_shell: true

# Git config
configure_workspace: true
git_email: name@mail.com
git_username: gitusername

# install packages
install_packages: true
installed_packages:
  - apache2-utils
  - cmake
  - git
  - guake
  - htop
  - locales-all
  - nmap
  - node
  - openssl
  - poedit
  - vagrant
  - vim
  - xclip
  - wget

# install packages from other package managers.
install_extra_packages: true
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Gnome config
gnome_setup: true
gnome_favorite_apps: [
  "firefox-esr.desktop",
  "google-chrome.desktop",
  "org.gnome.Nautilus.desktop",
  "code.desktop",
#  "pycharm-professional_pycharm-professional.desktop", # Pycharm name depends on the flavor
#  "signal-desktop.desktop",
]

# extra installs
install_keypass_xc: false
install_obs: false
install_openrgb: false
install_signal: false

# glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
