---
roles:
  - name: darkwizard242.googlechrome
    version: 1.1.2
  - name: geerlingguy.docker
    version: 3.1.2
  - name: robertdebock.obsproject
    version: 2.0.2
  - name: staticdev.python_developer
    version: 0.4.3

collections:
  - name: community.general
  - name: community.crypto
