---
roles:
  - name: staticdev.firefox
    version: 1.0.1
  - name: darkwizard242.googlechrome
    version: 1.1.2
  - name: geerlingguy.docker
    version: 3.1.2
  - name: robertdebock.obsproject
    version: 2.0.2
  - name: staticdev.python_developer
    version: 0.7.0
  - name: staticdev.signal
    version: 1.1.0

collections:
  - name: community.general
    version: 3.3.2
  - name: community.crypto
    version: 1.7.1
