---
roles:
  - name: staticdev.firefox
    version: 1.0.1
  - name: darkwizard242.googlechrome
    version: 1.1.2
  - name: geerlingguy.docker
    version: 3.1.2
  - name: robertdebock.obsproject
    version: 2.0.2
  - name: staticdev.python_developer
    version: 0.7.3
  - name: staticdev.signal
    version: 1.3.0

collections:
  - name: community.general
    version: 3.4.0
  - name: community.crypto
    version: 1.8.0
