---
roles:
  - name: darkwizard242.googlechrome
  - name: geerlingguy.docker
  - name: robertdebock.obsproject
  - name: staticdev.python_developer
    version: 0.3.0

collections:
  - name: community.general
  - name: community.crypto
