---
- name: Create user file for git config
  template:
    src: gitconfig/.gitconfig_user.t2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
- name: Creates a workspace directory
  file:
    path: "{{ ansible_env.HOME }}/workspace"
    state: directory
- name: Create workspace file for git config
  template:
    src: gitconfig/.gitconfig_workspace.t2
    dest: "{{ ansible_env.HOME }}/workspace/.gitconfig"
