---
- name: Add guake terminal to autostart.
  copy:
    src: /usr/share/applications/guake.desktop
    dest: /etc/xdg/autostart/
    mode: 0644
  become: true
  when: "'guake' in installed_packages"
