---
- name: Install python-psutil package
  apt:
    name: zsh
  become: true
- name: Create .zshrc
  template:
    src: zsh/.zshrc.t2
    dest: "{{ ansible_env.HOME }}/.zshrc"
- name: Set zsh as default
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  become: true
  when: zsh_default_shell
